# Assignment 1 – Working with NumPy

This notebook demonstrates basic NumPy array creation, manipulation, and mathematical operations.

In [6]:
import numpy as np

## 1. 1D Array Operations
Create a 1D array from 1 to 20 and compute basic statistics.

In [7]:
arr = np.arange(1, 21)
print('Array:', arr)

print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

indices = np.where(arr > 10)
print('Indices of elements > 10:', indices)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


## 2. 2D Array Operations
Create a 4×4 array and perform transpose and sum operations.

In [8]:
arr2d = np.arange(1, 17).reshape(4, 4)
print('2D Array:\n', arr2d)

print('Transpose:\n', arr2d.T)

print('Row-wise sum:', arr2d.sum(axis=1))
print('Column-wise sum:', arr2d.sum(axis=0))

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


## 3. Operations on Two 3×3 Random Arrays

In [9]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

print('Array A:\n', a)
print('Array B:\n', b)

print('Addition:\n', a + b)
print('Subtraction:\n', a - b)
print('Multiplication:\n', a * b)

print('Dot Product:\n', np.dot(a, b))

Array A:
 [[20  9 13]
 [18  3  3]
 [ 5  9 17]]
Array B:
 [[10 18 11]
 [ 5 20  1]
 [15 19  2]]
Addition:
 [[30 27 24]
 [23 23  4]
 [20 28 19]]
Subtraction:
 [[ 10  -9   2]
 [ 13 -17   2]
 [-10 -10  15]]
Multiplication:
 [[200 162 143]
 [ 90  60   3]
 [ 75 171  34]]
Dot Product:
 [[440 787 255]
 [240 441 207]
 [350 593  98]]


## 4. Reshaping and Slicing

In [10]:
arr1d = np.arange(1, 13)
reshaped = arr1d.reshape(3, 4)
print('Reshaped Array:\n', reshaped)

sliced = reshaped[:2, -2:]
print('Sliced Array:\n', sliced)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array:
 [[3 4]
 [7 8]]
